### ISSUE TITLE
Only show rooms you've been to

### ISSUE THREAD

**Issue by thislooksfun** [SFGrenade/AdditionalMaps#3]
When I picked up the White Palace map, it gave me the entirety of the White Palace, even though I hadn't visited most of the scenes yet. I would much prefer if it would instead show the rooms one-by-one after I've visited them, like the rest of the game maps.

**Comment by SFGrenade** [comment]
while that is a great idea i myself would like to do, but...
last i worked on this mod and with hollow knight maps in general they check based on their in-game scene name, which in case of everything white palace, godhome and dream areas, are all considered "visited" from the very start of the game.
but i probably could work around that one way or another.

**Comment by thislooksfun** [comment]
Upon reviewing the code, the White_Palace scenes are added to `scenesMapped`, but _not_ `scenesVisited`. You could filter out all the custom mapped scenes that mapped but unvisited, and let the normal Quill logic do the rest.

**Comment by SFGrenade** [comment]
i think i have something usable ready

**Comment by thislooksfun** [comment]
Ooh, exciting! Where can I find it?

**Comment by SFGrenade** [comment]
should work with <https://github.com/SFGrenade/AdditionalMaps/commit/b92c38934353398f3555bbfba579b557ad9561ff> and later but i'll also update it on scarab now

**Comment by thislooksfun** [comment]
It works! Thank you!
